import { ResourceDecorator as Resource, ExecutionContext, Injectable } from '@nitrostack/core';
import { RequirementService } from './requirement.service.js';

/**
 * RequirementResources
 *
 * Exposes `case://requirements/{caseId}`, a read-only view of the latest
 * requirement summary generated by the `resolve_requirements` tool for a
 * case. Backed entirely by RequirementService's in-memory cache — no
 * database read, no recomputation, no side effects.
 *
 * TODO(requirement): this resource assumes the NitroStack resource
 * decorator passes URI template parameters as the handler's first
 * argument (mirroring how Tool handlers receive `(input, ctx)`). If the
 * installed @nitrostack/core version instead exposes path parameters via
 * `ctx`, only `extractCaseId()` below needs to change — it already checks
 * both locations plus a raw-URI fallback, but this should be verified
 * against the real framework once dependencies are installed.
 * TODO(requirement): once the Visa Case Module gains tenant isolation,
 * this resource must scope reads by tenant/caller identity per
 * docs/RESOURCES.md §2 ("Tenant Isolation", "Least Privilege") — it
 * currently returns the cached summary to any authorized caller.
 */
@Injectable({ deps: [RequirementService] })
export class RequirementResources {
    constructor(private requirementService: RequirementService) { }

    @Resource({
        uri: 'case://requirements/{caseId}',
        name: 'Case Requirement Summary',
        description: 'Returns the latest in-memory requirement summary (required documents, estimated timeline, application steps, special notes) generated for a case by resolve_requirements. Read-only; does not compute or cache anything itself.',
        mimeType: 'application/json'
    })
    async getRequirementSummary(params: any, ctx: ExecutionContext) {
        const caseId = this.extractCaseId(params, ctx);

        if (!caseId) {
            throw new Error('case://requirements/{caseId} requires a caseId path parameter.');
        }

        const summary = this.requirementService.getCachedSummary(caseId);

        if (!summary) {
            return {
                caseId,
                available: false,
                message: 'No requirement summary has been generated yet for this case. Call the resolve_requirements tool first.'
            };
        }

        return {
            caseId: summary.caseId,
            available: true,
            nationality: summary.nationality,
            destinationCountry: summary.destinationCountry,
            visaType: summary.visaType,
            requiredDocuments: summary.requiredDocuments,
            estimatedTimeline: summary.estimatedTimeline,
            applicationSteps: summary.applicationSteps,
            specialNotes: summary.specialNotes,
            generatedAt: summary.generatedAt
        };
    }

    /**
     * Best-effort extraction of the `{caseId}` URI template parameter
     * across a few plausible NitroStack calling conventions. See the
     * class-level TODO above.
     */
    private extractCaseId(params: any, ctx: ExecutionContext): string | undefined {
        if (params && typeof params === 'object' && params.caseId) {
            return params.caseId;
        }

        const anyCtx = ctx as any;
        if (anyCtx?.params?.caseId) {
            return anyCtx.params.caseId;
        }

        const uri: string | undefined = anyCtx?.uri || anyCtx?.resourceUri || anyCtx?.request?.uri;
        if (uri) {
            const match = uri.match(/requirements\/([^/?#]+)/i);
            if (match) return decodeURIComponent(match[1]);
        }

        return undefined;
    }
}
